# Quick Start:
#
# pip install pre-commit
# pre-commit install && pre-commit install -t pre-push
# pre-commit run --all-files
#
# To Skip Checks:
#
# git commit --no-verify

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace

  - repo: https://github.com/myint/autoflake
    rev: "v2.0.1"
    hooks:
      - id: autoflake
        args:
          [
            "--recursive",
            "--in-place",
            "--remove-unused-variables",
            "--remove-all-unused-imports",
            "--ignore-init-module-imports",
          ]

  - repo: https://github.com/psf/black
    rev: "23.9.1"
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8

  - repo: https://github.com/python-poetry/poetry
    rev: "1.3.0"
    hooks:
      - id: poetry-export
        args: ["-o", "requirements.txt", "--without-hashes"]

  - repo: https://github.com/python-poetry/poetry
    rev: "1.3.0"
    hooks:
      - id: poetry-export
        args:
          ["-o", "requirements-dev.txt", "--without-hashes", "--with", "dev"]
